# Generated by Django 3.0.6 on 2020-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20200521_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn', 'author', 'category')},
        ),
    ]
